import express from 'express';
import cors from 'cors';
import { z } from 'zod';
import { env } from './config';
import { readDb, writeDb } from './db';
import { sign, verify } from './auth';
const app = express();
app.use(cors({origin:env.frontend,credentials:true}));
app.use(express.json());
const auth=(req:any,res:any,next:any)=>{const h=req.headers.authorization; const token=h?.startsWith('Bearer ')?h.slice(7):null; if(!token) return res.status(401).json({message:'Unauthorized'}); try{req.user=verify(token); next();}catch{return res.status(401).json({message:'Invalid token'})}};
const admin=(req:any,res:any,next:any)=>auth(req,res,()=>req.user?.role==='admin'?next():res.status(403).json({message:'Admin only'}));
app.get('/',(_req,res)=>res.json({name:'AZCON Smart Transit AI API',status:'ok'}));
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.get('/api/public/overview',(_req,res)=>{const db=readDb(); res.json({analytics:db.analytics,institutions:db.institutions,team:db.team,routes:db.routes,recommendations:db.recommendations.filter((x:any)=>x.audience==='user')});});
const reg=z.object({name:z.string().min(2),surname:z.string().min(2),email:z.string().email(),password:z.string().min(6),role:z.enum(['admin','user']).default('user'),avatar:z.string().optional(),theme:z.string().optional()});
app.post('/api/auth/register',(req,res)=>{try{const db=readDb(); const body=reg.parse(req.body); if(db.users.some((u:any)=>u.email===body.email)) return res.status(400).json({message:'Email exists'}); const user={id:`u_${Date.now()}`,...body}; db.users.push(user); writeDb(db); res.status(201).json({token:sign({id:user.id,email:user.email,role:user.role}),user:{...user,password:undefined}});}catch(e:any){res.status(400).json({message:e.message})}});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body; const db=readDb(); const user=db.users.find((u:any)=>u.email===email&&u.password===password); if(!user) return res.status(400).json({message:'Invalid credentials'}); res.json({token:sign({id:user.id,email:user.email,role:user.role}),user:{...user,password:undefined}})});
app.get('/api/dashboard',auth,(req:any,res)=>{const db=readDb(); res.json({stats:[{label:'Active corridors',value:db.routes.length,delta:'+3.1%'},{label:'Prediction accuracy',value:'91.4%',delta:'+1.8%'},{label:'Average delay',value:'5.2 min',delta:'-0.6 min'},{label:'Team members',value:db.team.length,delta:'live'}],routes:db.routes,alerts:db.alerts,analytics:db.analytics,recommendations:db.recommendations,team:db.team,overview:db.analytics.overview});});
app.get('/api/routes',auth,(_req,res)=>res.json(readDb().routes));
app.post('/api/routes',admin,(req,res)=>{const db=readDb(); const item={id:`r_${Date.now()}`,...req.body}; db.routes.push(item); writeDb(db); res.status(201).json(item);});
app.delete('/api/routes/:id',admin,(req,res)=>{const db=readDb(); db.routes=db.routes.filter((x:any)=>x.id!==req.params.id); writeDb(db); res.status(204).send();});
app.get('/api/team',auth,(_req,res)=>res.json(readDb().team));
app.post('/api/team',admin,(req,res)=>{const db=readDb(); const item={id:`t_${Date.now()}`,...req.body}; db.team.push(item); writeDb(db); res.status(201).json(item);});
app.delete('/api/team/:id',admin,(req,res)=>{const db=readDb(); db.team=db.team.filter((x:any)=>x.id!==req.params.id); writeDb(db); res.status(204).send();});
app.get('/api/ai/passenger-flow/:routeId',auth,(req,res)=>{const r=readDb().routes.find((x:any)=>x.id===req.params.routeId); res.json({routeId:req.params.routeId,passengerFlow:Math.round(r.capacity*(0.6+r.occupancy/200)),confidence:0.89})});
app.get('/api/ai/occupancy-forecast/:routeId',auth,(req,res)=>{const r=readDb().routes.find((x:any)=>x.id===req.params.routeId); res.json({routeId:req.params.routeId,occupancyForecast:Math.min(99,r.occupancy+(r.crowded?4:2))})});
app.get('/api/ai/delay-risk/:routeId',auth,(req,res)=>{const r=readDb().routes.find((x:any)=>x.id===req.params.routeId); res.json({routeId:req.params.routeId,delayRisk:r.delayRisk,avgDelayMinutes:r.avgDelayMinutes})});
app.post('/api/ai/recommendation',auth,(req,res)=>res.json({recommendation:'Prioritize metro and rail during peak wave; reserve taxis for airport transfers.',source:'mock-openrouter-ready',userContext:req.body}));
app.listen(env.port,()=>console.log(`AZCON backend listening on http://localhost:${env.port}`));
